app:
  rpc-port: "8080"
  http-port: "8081"
  captcha: false
  register: false
  key: pufLwZl$pP=Wxuv0SIuro8x6&NNxBmJI^Z(wbbNZ7s5UA8L1@Z
  database: false
  cache: false
  service-discovery: false
  token-expiration-time: 86.4µs
  use-http-code: false
  time-zone: Asia/Shanghai
  communication-timeout: 1µs
database:
  host: localhost
  port: "5432"
  name: your-database-name
  user: your-database-user
  password: your-database-password
  prefix: prefix_
service-discovery:
  address: localhost:8500
  service:
    id: ExampleService-1
    name: ExampleService
    address: 192.168.1.100
    tag:
    - primary
    check-interval: 60s
    check-url: /health
cache:
  address: localhost:6379
  password: "123456"
  db: 1
captcha:
  host: ""
  secret: captcha-key
  timeout: 0s
log:
  level: info
  panic: 3
  fatal: 3
  error: 3
  warning: 3
  info: 3
  debug: 3
  trace: 3
field:
  pagination:
    number: page_number
    size: page_size
    count: page_count
